name: Update
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
      
      - uses: actions/setup-node@latest
        with:
          node-version: '22'


      - name: Update
        run: |
          npm install
          git config --global user.email "kreato@kreato.dev"
          git config --global user.name "Kreato"
          npx quartz update
          git push
